version: '2'

services:
  frontend:
    restart: always
    build: ./smartplaylist
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - back-tier
      - front-tier
    volumes:
      - static:/usr/src/app/static
      - logs:/usr/src/app/logs
      - pickles:/usr/src/app/pickles
    env_file: web.env
    environment:
      - DB_IP=db
    command: bash -c "/usr/local/bin/gunicorn mysite.wsgi:application -w 2 -b :8000 --reload"

  nginx:
      restart: always
      build: ./nginx
      ports:
       - "80:80"
      environment:
        - APP_NAME=web
      volumes:
       - static:/www/static
      volumes_from:
       - frontend
      networks:
       - front-tier
      depends_on:
       - frontend

  db:
      restart: always
      image: postgres:latest
      env_file: db.env
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - back-tier
      ports:
        - "5432:5432"

volumes:
  db-data:
    driver: local
  logs:
    driver: local
  pickles:
    driver: local
  static:

networks:
  front-tier:
  back-tier:
