# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-29 21:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mxm_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('is_test', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mxm_tid', models.IntegerField(unique=True)),
                ('spotify_id', models.CharField(max_length=30, null=True)),
                ('artist', models.ManyToManyField(to='smart_playlist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_playlist.Song'),
        ),
        migrations.AddField(
            model_name='lyric',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_playlist.Word'),
        ),
        migrations.AddField(
            model_name='audiofeatures',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_playlist.Song'),
        ),
    ]
