# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mxm_tid',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
