# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_playlist', '0002_auto_20170418_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
